name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: .\build_binary.bat
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dearmor-lib-build
          path: dearmor/Release

  pypi:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dearmor-lib-build
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}